#!/usr/bin/env zsh

dotfiles=( zshrc zsh vimrc )

link () {
	if [[ -e ~/.$1 ]]; then
		if [[ -L ~/.$1 ]]; then
			unlink ~/.$1
		else 
			mv ~/.$1 ~/.$1.original
		fi
	fi
	ln -sf $(pwd)/$1 ~/.$1
	if [[ $? -ne 0 ]]; then
		printf "\n\tSomething went wrong linking $1...\n"
	fi
}

# Install oh-my-zsh if not present
if [[ ! -d ~/.oh-my-zsh ]]; then
	# https://github.com/ohmyzsh/ohmyzsh#unattended-install
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
fi

# Link dotfiles
for dotfile in "${dotfiles[@]}"; do
	link dotfile
done

# Celebrate
cake="H4sIAJt+7mIAA3VSMZLEIAzreQUzQGWwexjPuHRDz/9fcgayC3t7pyIJSJYFsfcHuRJQcdeOp07+A5gLN6L2lmEl9q0r5WXBBCkOld6D1EdTYggC9ggyiR42tOJiSYMzXzXSj02JL7o/oGwLmGsZbiYQq23bGoa59d3bc5IlsnAjWV19dTJE3GHT3JNUnb11loGKSKRifG5xs/mct7hl0jnnUkrGktJK1mO9Lg6ssZPwBSF8i+oslPgYXtDTruk8TmT35bTjc/yHV8Q2Nnf9qwpfzVaqdIk8g3RNf6TvV3i2+x+JHcNvw/6kzzSCQs3zD60oJxsfuu2RQPN7STqQLQQYz+TZJKbtoYQfA2kcVi74A6Y3ED+4AgAA"
printf "\nEnjoy\n%s\n" "$(base64 -d <<<"$cake" | gunzip)"

# Reload the current zsh session
exec zsh
